[package]
name = "disjunctgraph"
version = "0.1.0"
authors = ["Zino Onomiwo <zinoonomiwo@gmail.com>"]
edition = "2018"

[features]
default = ["labeller"]
labeller = ["dot"]

[dependencies]
dot = { version = "0.1.4", optional = true }
hashbrown = "0.3.0"
itertools = "0.8.0"