[package]
name = "z3solver"
version = "0.1.0"
authors = ["Zino Onomiwo <zinoonomiwo@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.4"
itertools = "0.8.0"
disjunctgraph = { path = "../disjunctgraph"}
z3 = "0.3.2"
