[package]
name = "cpbab"
version = "0.1.0"
authors = ["Zino Onomiwo <zinoonomiwo@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.3"
itertools = "0.8.0"
disjunctgraph = { path = "../disjunctgraph"}