[package]
name = "jobshop-gui"
version = "0.1.0"
authors = ["Zino Onomiwo <zinoonomiwo@gmail.com>"]
edition = "2018"

[dependencies]
disjunctgraph = { path = "../disjunctgraph"}
jobshop = { path = "../jobshop"}

gtk = "0.5"
relm = "0.15.2"
relm-derive = "0.15.2"
relm-attributes = "0.15.2"