[package]
name = "jobshop"
version = "0.1.0"
authors = ["Zino Onomiwo <zinoonomiwo@gmail.com>"]
edition = "2018"

[dependencies]
dot = "0.1.4"
rand = "0.6.5"
disjunctgraph = { path = "../disjunctgraph"}